version: '3'
services:
  frontend:
    build: ./application
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "5000:8080"
    restart: always
    environment:
      - NODE_ENV=production
