version: '3'
services:
  frontend:
    build: ./application
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
