version: '3'
services:
  frontend:
    build: ./application
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
